---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- gitea/helm-repository.yaml
- gitea/secret.yaml
- gitea/configmap.yaml
- gitea/certificates.yaml
- gitea/entrypoint.yaml
- gitea/helm-release.yaml
- code-server/helm-repository.yaml
- code-server/secret.yaml
- code-server/configmap.yaml
- code-server/helm-release.yaml
- code-server/dev-ingress.yaml