apiVersion: v1
kind: Secret
metadata:
    name: aws-sec
    namespace: cloud
stringData:
    config: ENC[AES256_GCM,data:ydgfCbacAK+tfZb46eN0khUBPvHZ5S7yd3mVN+sbZ+470WhJQdeZLgI/zA==,iv:gpK6qyS72wSWtHVpCGDRkVRqNzZYPct8XDErMO2LcRc=,tag:plFn2X5TNiZV8aQ77uf/pQ==,type:str]
    credentials: ENC[AES256_GCM,data:oT0HBV7bRMebdz7342sugkGRA50pI8ZcZO/BTX2tbP8dFQH7dwttW3ykT3wxYvs/kDLjOJWD6uvzyYrsOI9JwMWgi3FxohmYr5EdyG8LFzYgIiLn9kkJmkpEA+wZHaN7Hdf+mn6/uEUOHHgAkPpL2q6HVg==,iv:pvb0NR2pNxWUGraC2IRbLy5xSlwBZKvDVn77lft6vTY=,tag:8Rd/JeSOxuq7/XXtL/ZK9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-25T20:22:07Z"
    mac: ENC[AES256_GCM,data:/1a+I2OLVH2hC6e58djeefUYTCN5GRxQTW9+RLaCfUHcjptEL+0fAYs8sCt4YYXT2WVsr5JBVOu1P+fMW40h88GBgJ43wrVzfDoxCb2UA6Oq3arNe/9Kd4mkA7SDEeb2bHysv8/Cvt9/TdyPc57HkqUuNdYJhvBEb9s4H4aMpJw=,iv:ieYb4gH0kUOPbaV6WR4rBKdgKda1+yOp31drEfE1nps=,tag:uDRWYW3Noa8oEsCzMvgvuQ==,type:str]
    pgp:
        - created_at: "2021-07-25T20:22:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxomR751EK3jARAAncfrTuS327DNHlF+JYC8QmdeqfHs6DQrCY9O3M0MZVK1
            fxCiFGwavFNF8Q9AlFS5aCXOMAEKdBzh4d61+bDo5SiNDApxnMWyxmw5v/BxZISx
            fhctb7gBkvnn4G+YPNDPC6/KeSCwvJCfEw36xZ9vCx19cwiqr1kliDfk24VPE/3l
            hvywsFsDi8YFCrDbhDJv3ibvOXKO34SGQguGkD54xdjOuvU+FKP7yIBj+ylsixu5
            k/HJ60vrNRCFSLaipl659xShl6UTIW6mihivYY7F3zJ8M0YVMnwffrhKK/MCOLDF
            7f40hz6l6Xsb/hEkwzG2TOEB3uQs5NvVxpHfl+KeZG71z9+k76m58NKHSyg32Cxg
            FWt3DOalEpXPHnYLvR6eJ0QOm48Sj4ODOBTXZfhb83XzpsKM4oF4EsalIQPSn48k
            9qRkGvuYSXyUILF5P/jP1Enxy9/qZ2/A62quM4HmRcA0L29QlBvbC2JmBE88MYNr
            DBlKMRTma0LB9jqc7/QOu0e4tl+SwFvUXnAvVJb4R34z9CRfq2fdTt5tOIBsOd6P
            /J/C+PZTXxLID3Wan0+WmJHTDtM6YM7/51Oskne6o/KQaXxS427huM3qlinpYnHE
            /IXzaoNFzlogi7pKEftjV60y5TsCdZ1WJtsmGK8ZwbG/yqITHKXdRJvOSOVbjvrS
            XgFXwTO9C5gT7/4Yldy9pUUY05aerq9+QGZNzDoGoR3JR1XQ4yySAxDgGJ3HWvVM
            sCfzqoTfaCsVWREtz/toEtu2dSJ73g/Y3Pw1FDD8GF1UyHm3z68vZFkzNdfUSCM=
            =H1XN
            -----END PGP MESSAGE-----
          fp: 663C004C3E28A539398B0C889E22CDED3974F565
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
