apiVersion: v1
kind: ConfigMap
metadata:
  name: code-cm
  namespace: cicd
data:
  values.yaml: |
    image:
      repository: registry.home.local/code-server
      pullPolicy: Always
      tag: "version-v3.11.0-dev"
    service:
      additionalServices:
      - enabled: true
        nameSuffix: react
        type: ClusterIP
        # Specify the default port information
        port:
          port: 3000
          # name defaults to http
          name: http-react
          protocol: TCP
          # targetPort defaults to http
          targetPort: 3000
          # nodePort:
        additionalPorts: []
        annotations: {}
        labels: {}
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: ca-issuer
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: code.dev.home.local
          paths:
          - path: /
            # Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
          - path: /react
            pathType: Prefix
            backend:
              service:
                port:
                  name: cicd-code-code-server-react
                  number: 3000
      tls:
      - secretName: code-tls
        hosts:
          - code.dev.home.local
      # additionalIngresses:
      # - enabled: true
      #   nameSuffix: "react"
      #   annotations:
      #     kubernetes.io/ingress.class: nginx
      #     cert-manager.io/cluster-issuer: ca-issuer
      #     nginx.ingress.kubernetes.io/proxy-body-size: "0"
      #   labels: {}
      #   hosts:
      #     - host: code.dev.home.local
      #       paths:
      #         - path: /react
      #           # Ignored if not kubeVersion >= 1.14-0
      #           pathType: Prefix
      #           backend:
      #             service:
      #               port:
      #                 number: 3000
      #   tls:
      #   - secretName: code-tls
      #     hosts:
      #       - code.dev.home.local   
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteMany
        size: 10Gi
    additionalVolumes:
    - name: certs-mnt
      secret:
        secretName: deb-certs
    additionalVolumeMounts:
    - name: certs-mnt
      mountPath: /etc/ssl/certs/ca-certificates.crt
      subPath: ca-certificates.crt
  
