apiVersion: v1
kind: ConfigMap
metadata:
  name: code-cm
  namespace: cicd
data:
  values.yaml: |
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: ca-issuer
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - code.dev.home.local
      tls:
      - secretName: git-tls
        hosts:
          - code.dev.home.local
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteMany
        size: 10Gi
    additionalVolumes:
    - name: certs-mnt
      secret:
        secretName: deb-certs
    additionalVolumeMounts:
    - name: certs-mnt
      mountPath: /etc/ssl/certs/ca-certificates.crt
      subPath: ca-certificates.crt
  
