---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code
  namespace: cicd
spec:
  chart:
    spec:
      chart: code-server
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde
  interval: 30s
  targetNamespace: cicd
  valuesFrom:
  - kind: ConfigMap
    name: code-cm
  - kind: Secret
    name: code-sec
