apiVersion: v1
kind: ConfigMap
metadata:
  name: next-cm
  namespace: cloud
data:
  values.yaml: |
    image:
      repository: nextcloud
      tag: 21.0.3-apache
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: ca-issuer
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - cloud.dev.home.local
      tls:
      - secretName: cloud-tls
        hosts:
          - cloud.dev.home.local
    nextcloud:
      host: cloud.dev.home.local
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: 500Gi
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    livenessProbe:
      enabled: true
      initialDelaySeconds: 125
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 90
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    startupProbe:
      enabled: false
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1