---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: cloud
spec:
  chart:
    spec:
      chart: nextcloud
      version: 2.6.5
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  interval: 30s
  targetNamespace: cloud
  valuesFrom:
  - kind: ConfigMap
    name: next-cm
  - kind: Secret
    name: next-sec
