apiVersion: v1
kind: Secret
metadata:
    name: next-sec
    namespace: cloud
stringData:
    values.yaml: ENC[AES256_GCM,data:sPr6gDnKp7V9z6QPCzYboTxfewP0sPlQvhU08sx10THdMkP96640G+/cit9BYk+N1e0JAznORoTgW4k6i5QdO5PYoq30XjEEpPtD4qvwsa35S0LMcy8MZBGOja3auErsZV5SnSu5G/3CfFnbioTeTwqI/4XmdAgFjwENENFE15/Ue++wK8RNJ3KTOnws3n4Wz+doZFqP7ueTg28werj7eLZ3/CdYOENf0ymVPIjaR9iV7euBytqAcvE5HYHBSD27YYPp4F3xe54Qfcb2PObNGCIiDmkY4vaQAYqVY3gFVClx7G9uyLEFFVZjpj8+nYoo4ycYoaqW+NOSqYcrtbbQgs8CrhbSyUGhiiFsa2A6K31LHyNGgrLA+laFCaa9qALZcT89P73fkATr42RVjkOBH1bPCbMhs2CH8RNK+RcUypLc3rnl4q0p25xK+bkBhivGfrqEP9n6jWAsO3RPlbbrLKngTY8UBwPrnWwvibq5dsQVK5eQSHQ=,iv:qd9cXO9v9USo/kY493Dy6/j/bupoAevu2G+Q+5Yx9sQ=,tag:ZdFwv+784SwErcDJ6I4xlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-18T20:23:57Z"
    mac: ENC[AES256_GCM,data:T6q8pqFMQ3/4Q6UHUK9eA7kVkiyLV0ZCjYUSzGVpnLbpXkEIuTszAzE6z3k3PaYxaOwOUjDrYg2jmiHwr+FD3xTC9ZmktB9Cu0yOWMnB1rj/YpH4WzEhm1PrKZ/bWghhC8tRVBp6owiwIBlDn49+TNZzuOzfeyOka4IkQu5+Phs=,iv:V3m4R3mDK8RbbycKqUF89nAx1elcAYD/IAgez3lSslc=,tag:2GWZoUPue9E0TNmILRrJjg==,type:str]
    pgp:
        - created_at: "2021-07-18T20:23:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxomR751EK3jARAAqMZNY+967ZwW4MoaF1i8OGiS3WF6LQVosrpSZZ2AKHnL
            ccQm6E6D9I3C6sGW/I3syfxW/VbdJzTFbIr5KrE1xmQGtSbLbdFIfG6RMMpA4tXm
            kKwkWgdxMtDKTXYxPRzkQK9/ZGPzitxPE0pjM7mCZEdxDSr/QfYKQfilf0tAXkaB
            naqU5QxjtbayM8AJcfA0RrwnPn22/YZvGMc6S0afXzJzU7Jkanmx8fYMtrXslm/y
            IANaArmzNYULJuIgniSbKRhIxygYLM4ooZnsmYA1ooeT15ZsN7HzO9MNdWKmbAji
            d0onnk2W1p46VdOiwTA59/Fr0FvmDPjYc8eN0IuQpJoEJnD6w9GcOH2E0v1pFePD
            lw3y7XhJdosUCZWaC9LJR2ReoRl7Sp6s/k+PPfAaS+BV2ipgkqHQDAeCld7zg4QW
            QSq5ALo0cCYkBNoFYnM/P/Y7TCL7jK5emNHpf2sWERR8VcQKHCuZlEmQnCcOtC6l
            HRU1afSO4ydUzJYxSThs0tIUrBitT7O4tfa8I6kZXGAU5/ZA6PmSZN4gYnFCuX/M
            BBae/r8JIeCpoRBm4TPN84RjeFJ/qGdB9fpWZ5vczSJZaP6T+MLoABVryOkpeV0C
            F5UxwDn7ycpZM389x6eJ7tC8svA+1FaAYDVJAmeJ3L1c2riyhdW2YCv2XH8PmKbS
            XgFuSAkrDp1VKuSrQtrdFYD242kr4cDTS3wDZ5kt9e96nAufMf76bpkDxLCNtgJf
            /BTBqi7UO6yrEgxeA4d8xnen8C672IpZFrxFBhQwtB/mih8roywka6wH1CdNWSI=
            =1edF
            -----END PGP MESSAGE-----
          fp: 663C004C3E28A539398B0C889E22CDED3974F565
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
