apiVersion: v1
kind: Secret
metadata:
    name: next-sec
    namespace: cloud
stringData:
    values.yaml: ENC[AES256_GCM,data:C8kHG/kPO7DC0JMp/KZbawE7Qw/OaY/v+anuOuupGS/YfwmbWdVff/vrFr+0Tp7S8bbePMhTkRCZuLPvEZZCBzJ4e2b8RXiJGErJVXC6FJuglu8FT6LlkZIG+aXKQINvPeUMnf7Xa21P3wbz7tpgBT/IIsARUZT9xVuwJS9Oo9zX4G+uA71qHjT4zCF4hdg+uBpAE3/iEzOADp96+g+S9eJnmchWpQicqX1oZfaO1HvLf5424Nq2vMxKyvbgVeTwrgdbGJFAZIG5NjunytwItAKZxa2DXI0Knrl0DrW14bsO/me64ZB/VC3r2NvPUfeu+ALVqPuV3xOdqXGCzaHHuJfkvDMhWAC2mJOZQtyFcTt5QOmTaqBLMFpM0+BVIFZJwpihSj6qKLtSN/7xGRzfZE24NreC9EUhTL89zS/OgwuVo7CYboVkOMc0oC+GpjrGjOrTowdce77YXOR2De1QLr40JdhgiFAHbspaMG1le9mbEHu3gNot6bqNg8OhyxLRY2ukpC/92RMnPpc=,iv:Q+AELYbGQd4sONNcPF6xAFZKnPHIy+Bo35I8vK6YU6g=,tag:rwL31tuLAuaZ+i2oLNwu7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-24T22:20:44Z"
    mac: ENC[AES256_GCM,data:w2hTfowIma+dGlEaXHxVm0p91d84syUx2n9/BfiSDMRgwNZyGF5s6rH5+hXXHPc2LtPtSQrvs703azn1GAvqATleqJgO2t/YB5qgkg+lfWGS5AgUj3IuQ5VR0zHFLIp4qU+tCL/fDvA5gcEKBEcpaIL2I0fqpaU2nfKDu8u/zOk=,iv:fA3F4zzNkvc08za0NXVeSxCE4JvL0aO0SwfqORkNcAs=,tag:6ZqrNzJYb4G8FI0EfXCMFw==,type:str]
    pgp:
        - created_at: "2021-07-24T22:20:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxomR751EK3jARAA5AFazs2XFJy3rdm2iSwDGlbDRHj9zjUBWh3DL9uMddAp
            JMGYw88e0ifOdzO3Ku826EkRYzfij3V2kP0YD3NHDXBh2OUBD0ISGKAmun8+svUk
            Wb8A+kVPPo9Qlxv2JuHGBaKXI5wQpf9BsbrmCecJOnGRAKgMp8HAzvNzc9KWimpf
            zwXF+lzgk/BCVgvgg7kYMbr1FwyJjiYfSLv1pFUsm9jJ72MyTuezr5nu6S8KqGGZ
            KCw1q4qbMdI5BCstECNRC3ZXrSkT4znmiaSAHyG2BMOsSjGXu0wzvy3EPeHlJaAy
            10BqH9kenZEUZooyvGvibPkUNHU0OMJEFD1WOZrDyFc8jPQEygWo5+u+rtMzjs8e
            GhYy11e47XvaHB3b67bZk80uUDYKrYBUieuyNRP3wZA5Uw9ugWDhevufbNOcWPAL
            9/LYO1imgK1jy62pHJLB43zxhZU77tA/zYnn6BHVpigC2KaZcNm76kQuDawQhpCt
            ci3QU0GJRnfp5Ggojer0obiyR8JrPleqmEbrTWYMhM4TNdDFg+8dmc4WgpoFC9D1
            zuD3mMTC/W8nTHQH3qpxuo7H8sq6mZMqy2H/t4oITi4eHdmCJIJioPwIqiTc6viO
            3WOgMGb6l+gUddbEuKTzaGzedyPgDqHC5GjS9w5aFEtAu+v+WEsedq6J4IoLPG/S
            XAHPq2m/ciUAKQ5RrRuZpTM0qGAq/IlC/tKT/jd9z4aMr+5/yaY8u+p8bQULzRpB
            kCvsJKbFOylMER1YkTK4jwdvod8cGurwlHxwiaNXzO/vRZgjn5gbZe6Tt7WD
            =eNtX
            -----END PGP MESSAGE-----
          fp: 663C004C3E28A539398B0C889E22CDED3974F565
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
