apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
  namespace: test
spec:
  steps:
    - name: hello
      image: busybox
      command:
        - echo
      args:
        - "Hello World!"