---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cicd
  namespace: cicd
spec:
  interval: 5m0s
  path: ./clusters/dev/gaming
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg