---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea-system
  namespace: cicd-system
spec:
  chart:
    spec:
      chart: gitea
      version: 3.1.4
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
  interval: 30s
  targetNamespace: cicd-system
  valuesFrom:
  - kind: ConfigMap
    name: gitea-cm
  - kind: Secret
    name: gitea-sec
