---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tekton
  namespace: tekton-pipelines
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/brandtkeller/toolchain-template
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tekton
  namespace: tekton-pipelines
spec:
  interval: 5m0s
  path: ./clusters/dev/tekton-pipelines
  prune: true
  sourceRef:
    kind: GitRepository
    name: tekton
  validation: client