---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tekton-pipeline
  namespace: tekton-pipelines
spec:
  interval: 5m0s
  path: ./clusters/dev/tekton-pipelines/pipelines
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tekton-trigger
  namespace: tekton-pipelines
spec:
  dependsOn:
    - name: tekton-pipeline
  interval: 5m0s
  path: ./clusters/dev/tekton-pipelines/triggers/trigger
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tekton-interceptor
  namespace: tekton-pipelines
spec:
  dependsOn:
    - name: tekton-trigger
  interval: 5m0s
  path: ./clusters/dev/tekton-pipelines/triggers/interceptor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  dependsOn:
    - name: tekton-interceptor
  interval: 5m0s
  path: ./clusters/dev/tekton-pipelines/dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client