apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: default
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/