---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-prov
  namespace: default
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.12
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  interval: 30s
  targetNamespace: default
  values:
    nfs:
      server: 192.168.0.50
      path: /nfsshare/k8s-volumes
    podSecurityPolicy:
      enabled: false
